name: XSS Scan

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run XSS scan
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep \
          semgrep --config="p/xss" --severity ERROR /src
          # task 3 and 6 added above
          # task 6 : semgrep --config="p/xss" --config="p/sql-injection" /src